;;; -*- Mode: LISP; Syntax: Common-Lisp; Package: USER; Base: 10; Patch-File: T -*-
;;; Patch file for Private version 0.0
;;; Written by Lisp Machine, 3/19/14 16:24:59
;;; while running on CHAOS from CHAOS-HOST:who-calls-chaos.vlod
;;; with Open Genera 2.0, Genera 8.5, Logical Pathnames Translation Files NEWEST,
;;; Ivory Revision 5, VLM Debugger 329, Genera program 9.0, DEC OSF/1 V127,
;;; 1280x956 24-bit TRUE-COLOR X Screen INTERNET|127.0.0.1:0.0 with 224 Genera fonts (The X.Org Foundation R11403901),
;;; Machine serial number 672934633,
;;; Allow multiple ll addresses (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/allow-multiple-ll-addresses.),
;;; Linux, not Alpha (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/alpha.),
;;; doc ex drawings (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/docs-ellipse.),
;;; more emb eth packets and disk buffers (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/emb-bufs.),
;;; disable lossage in get-emb-host (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/get-emb-host.),
;;; OpenSuse FSS (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/opensuse-fss-patch.),
;;; primary network: parse :internet before :chaos (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/primary-network-address.),
;;; Rational quotient (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/rational-quotient.),
;;; disable GC during user disk io (from DISTRIBUTION|DIS-EMB-HOST:/home/lispm/lsource/user-disk-without-gc.).


(SCT:FILES-PATCHED-IN-THIS-PATCH-FILE 
  "SYS:X11;CLX;KEYSYMS.LISP.5001"
  "SYS:X11;SCREEN;X-CONSOLE.LISP.47"
  "SYS:X11;SCREEN;X-KEYSYM-NAMES.LISP.8")


(SCT:NOTE-PRIVATE-PATCH "detect keyboard")


;========================
(SCT:BEGIN-PATCH-SECTION)
(SCT:PATCH-SECTION-SOURCE-FILE "SYS:X11;CLX;KEYSYMS.LISP.5001")
(SCT:PATCH-SECTION-ATTRIBUTES
  "-*- Mode:Lisp; Package:XLIB; Syntax:COMMON-LISP; Base:10; Lowercase:YES -*-")


;#+vlm
  (defconstant iso-level3-shift-keysym (keysym 254 003))
  (define-keysym :iso-level3-shift iso-level3-shift-keysym)

  (defconstant keypad-home-keysym (keysym 255 149))
  (define-keysym :keypad-home keypad-home-keysym)

  (defconstant keypad-left-keysym (keysym 255 150))
  (define-keysym :keypad-left keypad-left-keysym)

  (defconstant keypad-up-keysym (keysym 255 151))
  (define-keysym :keypad-up keypad-up-keysym)

  (defconstant keypad-right-keysym (keysym 255 152))
  (define-keysym :keypad-right keypad-right-keysym)

  (defconstant keypad-down-keysym (keysym 255 153))
  (define-keysym :keypad-down keypad-down-keysym)

  (defconstant keypad-prior-keysym (keysym 255 154))
  (define-keysym :keypad-prior keypad-prior-keysym)

  (defconstant keypad-next-keysym (keysym 255 155))
  (define-keysym :keypad-next keypad-next-keysym)

  (defconstant keypad-end-keysym (keysym 255 156))
  (define-keysym :keypad-end keypad-end-keysym)

  (defconstant keypad-begin-keysym (keysym 255 157))
  (define-keysym :keypad-begin keypad-begin-keysym)

  (defconstant keypad-insert-keysym (keysym 255 158))
  (define-keysym :keypad-insert keypad-insert-keysym)

  (defconstant keypad-delete-keysym (keysym 255 159))
  (define-keysym :keypad-delete keypad-delete-keysym)

  (defconstant dead-circumflex-keysym (keysym 254 82))
  (define-keysym :dead-circumflex dead-circumflex-keysym)

  (defconstant dead-acute-keysym (keysym 254 81))
  (define-keysym :dead-acute dead-acute-keysym)

;========================
(SCT:BEGIN-PATCH-SECTION)
(SCT:PATCH-SECTION-SOURCE-FILE "SYS:X11;SCREEN;X-CONSOLE.LISP.47")
(SCT:PATCH-SECTION-ATTRIBUTES
  "-*- Base: 10; Package: X-SCREEN; Mode: LISP; Syntax: Common-lisp; Lowercase: T -*-")

;(defparameter
;  *modifier-mapping-alist*
;  '((:shift :left-shift :right-shift)
;    (:lock :caps-lock :num-lock)
;    (:control :left-control :right-control)
;    (:meta :left-meta :right-meta)
;    (:super :left-super :right-super)
;    (:hyper :left-hyper :right-hyper)
;    (:symbol :left-symbol :right-symbol)
;    (:function :mode-lock #\Abort #\Select #\Function #\Network #\Suspend #\Resume #\Help)))

(defun-in-flavor (fill-keyboard-table-specific x-console) (table layout-type)
  (loop with nxshifts = (array-dimension (xlib::display-keyboard-mapping display) 1)
	with nlshifts = (array-dimension table 0)
	with null-mapping = (sys:standardize-keyboard-mapping nil t)
	with keyboard-mapping =
	  (keyboard-mapping-keys 
	    (or (layout-type-keyboard-mapping layout-type)
		(layout-type-keyboard-mapping :default)))
	for code from (xlib:display-min-keycode display)
		 to (xlib:display-max-keycode display)
	for code-keys = (cdr (assoc (keycode->keynum code) keyboard-mapping))
	do (when code-keys
	     ;; key code specific key mappings have the highest priority
	     (loop for lshift below nlshifts
		   for key = (or (nth lshift code-keys) (first code-keys))
		   when (and key t)
;;			     (= (aref table lshift (keycode->keynum code))
;;				null-mapping))
		     do (setf (aref table lshift (keycode->keynum code))
			      (sys:standardize-keyboard-mapping key t))))
	   ;; Next comes shift specific key mappings 
	   (loop with unshifted-keysym = (xlib:keycode->keysym display code 0)
		 for xshift below nxshifts
		 for lshift below nlshifts
		 when (= (aref table lshift (keycode->keynum code)) null-mapping)
		   do (loop with shifted-keysym = (xlib:keycode->keysym display code xshift)
			    with shifted-keysym-names =
			      (gethash shifted-keysym *keysym-name-table*)
			    for shifted-keysym-name in shifted-keysym-names
			    for shifted-key =
				(cadr (assoc shifted-keysym-name keyboard-mapping))
			    when (and shifted-key
				      (not (= unshifted-keysym shifted-keysym))
;;				      (= (aref table lshift (keycode->keynum code))
;;					 null-mapping))
				      )
			      do (setf (aref table lshift (keycode->keynum code))
				       (sys:standardize-keyboard-mapping shifted-key t))
			      and return))
	   ;; finally mappings based on the unshifted keysym
	   (loop with unshifted-keysym = (xlib:keycode->keysym display code 0)
		 with unshifted-keysym-names = (gethash unshifted-keysym *keysym-name-table*)
		 for lshift below nlshifts
		 do (loop for unshifted-keysym-name in unshifted-keysym-names
			  for unshifted-keys =
			      (cdr (assoc unshifted-keysym-name keyboard-mapping))
			  for key = (or (nth lshift unshifted-keys) (first unshifted-keys))
			  when (and key t)
;;				    (= (aref table lshift (keycode->keynum code))
;;				       null-mapping))
			    do (setf (aref table lshift (keycode->keynum code))
				     (sys:standardize-keyboard-mapping key t))))))


;========================
(SCT:BEGIN-PATCH-SECTION)
(SCT:PATCH-SECTION-SOURCE-FILE "SYS:X11;SCREEN;X-KEYSYM-NAMES.LISP.8")
(SCT:PATCH-SECTION-ATTRIBUTES
  "-*- Mode: Lisp; Package: X-SCREEN; Syntax: Common-Lisp; Lowercase: Yes -*-")

;;
;; added the following keysyms:
;;
; (254 3 "iso level3 shift" :ISO-LEVEL3-SHIFT)
; (255 149 "Keypad Home" :KEYPAD-HOME)
; (255 150 "Keypad Left" :KEYPAD-LEFT)
; (255 151 "Keypad Up" :KEYPAD-UP)
; (255 152 "Keypad Right" :KEYPAD-RIGHT)
; (255 153 "Keypad Down" :KEYPAD-DOWN)
; (255 154 "Keypad Prior" :KEYPAD-PRIOR)
; (255 155 "Keypad Next" :KEYPAD-NEXT)
; (255 156 "Keypad End" :KEYPAD-END)
; (255 157 "Keypad Begin" :KEYPAD-BEGIN)
; (255 158 "Keypad Insert" :KEYPAD-INSERT)
; (255 159 "Keypad Delete" :KEYPAD-DELETE)
;;
;;

(defparameter
  *keysym-name-list*
  '((000 032 " " :space)
    (000 033 "!" :exclamation-point)
    (000 034 "\"" :quotation-mark)
    (000 035 "#" :number-sign)
    (000 036 "$" :dollar-sign)
    (000 037 "%" :percent-sign)
    (000 038 "&" :ampersand)
    (000 039 "'" :apostrophe)
    (000 040 "(" :left-parenthesis)
    (000 041 ")" :right-parenthesis)
    (000 042 "*" :asterisk)
    (000 043 "+" :plus-sign)
    (000 044 "," :comma)
    (000 045 "-" :hyphen :minus-sign)
    (000 046 "." :full-stop)
    (000 047 "/" :solidus)
    (000 048 "0" :digit-zero)
    (000 049 "1" :digit-one)
    (000 050 "2" :digit-two)
    (000 051 "3" :digit-three)
    (000 052 "4" :digit-four)
    (000 053 "5" :digit-five)
    (000 054 "6" :digit-six)
    (000 055 "7" :digit-seven)
    (000 056 "8" :digit-eight)
    (000 057 "9" :digit-nine)
    (000 058 ":" :colon)
    (000 059 ";" :semicolon)
    (000 060 "<" :less-than-sign)
    (000 061 "=" :equals-sign)
    (000 062 ">" :greater-than-sign)
    (000 063 "?" :question-mark)
    (000 064 "@" :commercial-at)
    (000 065 "A" :latin-capital-letter-a)
    (000 066 "B" :latin-capital-letter-b)
    (000 067 "C" :latin-capital-letter-c)
    (000 068 "D" :latin-capital-letter-d)
    (000 069 "E" :latin-capital-letter-e)
    (000 070 "F" :latin-capital-letter-f)
    (000 071 "G" :latin-capital-letter-g)
    (000 072 "H" :latin-capital-letter-h)
    (000 073 "I" :latin-capital-letter-i)
    (000 074 "J" :latin-capital-letter-j)
    (000 075 "K" :latin-capital-letter-k)
    (000 076 "L" :latin-capital-letter-l)
    (000 077 "M" :latin-capital-letter-m)
    (000 078 "N" :latin-capital-letter-n)
    (000 079 "O" :latin-capital-letter-o)
    (000 080 "P" :latin-capital-letter-p)
    (000 081 "Q" :latin-capital-letter-q)
    (000 082 "R" :latin-capital-letter-r)
    (000 083 "S" :latin-capital-letter-s)
    (000 084 "T" :latin-capital-letter-t)
    (000 085 "U" :latin-capital-letter-u)
    (000 086 "V" :latin-capital-letter-v)
    (000 087 "W" :latin-capital-letter-w)
    (000 088 "X" :latin-capital-letter-x)
    (000 089 "Y" :latin-capital-letter-y)
    (000 090 "Z" :latin-capital-letter-z)
    (000 091 "[" :left-square-bracket)
    (000 092 "\\" :reverse-solidus)
    (000 093 "]" :right-square-bracket)
    (000 094 "^" :circumflex-accent)
    (000 095 "_" :low-line)
    (000 096 "`" :GRAVE-ACCENT)
    (000 097 "a" :latin-small-letter-a)
    (000 098 "b" :latin-small-letter-b)
    (000 099 "c" :latin-small-letter-c)
    (000 100 "d" :latin-small-letter-d)
    (000 101 "e" :latin-small-letter-e)
    (000 102 "f" :latin-small-letter-f)
    (000 103 "g" :latin-small-letter-g)
    (000 104 "h" :latin-small-letter-h)
    (000 105 "i" :latin-small-letter-i)
    (000 106 "j" :latin-small-letter-j)
    (000 107 "k" :latin-small-letter-k)
    (000 108 "l" :latin-small-letter-l)
    (000 109 "m" :latin-small-letter-m)
    (000 110 "n" :latin-small-letter-n)
    (000 111 "o" :latin-small-letter-o)
    (000 112 "p" :latin-small-letter-p)
    (000 113 "q" :latin-small-letter-q)
    (000 114 "r" :latin-small-letter-r)
    (000 115 "s" :latin-small-letter-s)
    (000 116 "t" :latin-small-letter-t)
    (000 117 "u" :latin-small-letter-u)
    (000 118 "v" :latin-small-letter-v)
    (000 119 "w" :latin-small-letter-w)
    (000 120 "x" :latin-small-letter-x)
    (000 121 "y" :latin-small-letter-y)
    (000 122 "z" :latin-small-letter-z)
    (000 123 "{" :left-curly-bracket)
    (000 124 "|" :vertical-line)
    (000 125 "}" :right-curly-bracket)
    (000 126 "~" :tilde)
    (000 160 "no break space" :no-break-space)
    (000 161 "inverted exclamation mark" :inverted-exclamation-mark)
    (000 162 "cent sign" :cent-sign)
    (000 163 "pound sign" :pound-sign)
    (000 164 "currency sign" :currency-sign)
    (000 165 "yen sign" :yen-sign)
    (000 166 "broken vertical bar" :broken-vertical-bar)
    (000 167 "paragraph sign" :paragraph-sign :section-sign)
    (000 168 "diaeresis" :diaeresis)
    (000 169 "copyright sign" :copyright-sign)
    (000 170 "feminine ordinal indicator" :feminine-ordinal-indicator)
    (000 171 "left angle quotation mark" :left-angle-quotation-mark)
    (000 172 "not sign" :not-sign)
    (000 174 "registered trade mark sign" :registered-trade-mark-sign)
    (000 175 "macron" :macron)
    (000 176 "degree sign" :degree-sign :ring-above)
    (000 177 "plus minus sign" :plus-minus-sign)
    (000 178 "superscript two" :superscript-two)
    (000 179 "superscript three" :superscript-three)
    (000 180 "acute accent" :acute-accent)
    (000 181 "micro sign" :micro-sign)
    (000 182 "pilcrow sign" :pilcrow-sign)
    (000 183 "middle dot" :middle-dot)
    (000 184 "cedilla" :cedilla)
    (000 185 "superscript one" :superscript-one)
    (000 186 "masculine ordinal indicator" :masculine-ordinal-indicator)
    (000 187 "right angle quotation mark" :right-angle-quotation-mark)
    (000 188 "vulgar fraction one quarter" :vulgar-fraction-one-quarter)
    (000 189 "vulgar fraction one half" :vulgar-fraction-one-half)
    (000 190 "vulgar fraction three quarters" :vulgar-fraction-three-quarters)
    (000 191 "inverted question mark" :inverted-question-mark)
    (000 192 "A with grave accent" :latin-capital-letter-a-with-grave-accent)
    (000 193 "A with acute accent" :latin-capital-letter-a-with-acute-accent)
    (000 194 "A with circumflex accent" :latin-capital-letter-a-with-circumflex-accent)
    (000 195 "A with tilde" :latin-capital-letter-a-with-tilde)
    (000 196 "A with diaeresis" :latin-capital-letter-a-with-diaeresis)
    (000 197 "A with ring above" :latin-capital-letter-a-with-ring-above)
    (000 198 "AE" :latin-capital-diphthong-ae)
    (000 199 "C with cedilla" :latin-capital-letter-c-with-cedilla)
    (000 200 "E with grave accent" :latin-capital-letter-e-with-grave-accent)
    (000 201 "E with acute accent" :latin-capital-letter-e-with-acute-accent)
    (000 202 "E with circumflex accent" :latin-capital-letter-e-with-circumflex-accent)
    (000 203 "E with diaeresis" :latin-capital-letter-e-with-diaeresis)
    (000 204 "I with grave accent" :latin-capital-letter-i-with-grave-accent)
    (000 205 "I with acute accent" :latin-capital-letter-i-with-acute-accent)
    (000 206 "I with circumflex accent" :latin-capital-letter-i-with-circumflex-accent)
    (000 207 "I with diaeresis" :latin-capital-letter-i-with-diaeresis)
    (000 208 "ETH" :icelandic-capital-letter-eth)
    (000 209 "N with tilde" :latin-capital-letter-n-with-tilde)
    (000 210 "O with grave accent" :latin-capital-letter-o-with-grave-accent)
    (000 211 "O with acute accent" :latin-capital-letter-o-with-acute-accent)
    (000 212 "O with circumflex accent" :latin-capital-letter-o-with-circumflex-accent)
    (000 213 "O with tilde" :latin-capital-letter-o-with-tilde)
    (000 214 "O with diaeresis" :latin-capital-letter-o-with-diaeresis)
    (000 215 "multiplication sign" :multiplication-sign)
    (000 216 "O with oblique stroke" :latin-capital-letter-o-with-oblique-stroke)
    (000 217 "U with grave accent" :latin-capital-letter-u-with-grave-accent)
    (000 218 "U with acute accent" :latin-capital-letter-u-with-acute-accent)
    (000 219 "U with circumflex accent" :latin-capital-letter-u-with-circumflex-accent)
    (000 220 "U with diaeresis" :latin-capital-letter-u-with-diaeresis)
    (000 221 "Y with acute accent" :latin-capital-letter-y-with-acute-accent)
    (000 222 "THORN" :icelandic-capital-letter-thorn)
    (000 223 "sharp s" :german-small-letter-sharp-s)
    (000 224 "a with grave accent" :latin-small-letter-a-with-grave-accent)
    (000 225 "a with acute accent" :latin-small-letter-a-with-acute-accent)
    (000 226 "a with circumflex accent" :latin-small-letter-a-with-circumflex-accent)
    (000 227 "a with tilde" :latin-small-letter-a-with-tilde)
    (000 228 "a with diaeresis" :latin-small-letter-a-with-diaeresis)
    (000 229 "a with ring above" :latin-small-letter-a-with-ring-above)
    (000 230 "ae" :latin-small-diphthong-ae)
    (000 231 "c with cedilla" :latin-small-letter-c-with-cedilla)
    (000 232 "e with grave accent" :latin-small-letter-e-with-grave-accent)
    (000 233 "e with acute accent" :latin-small-letter-e-with-acute-accent)
    (000 234 "e with circumflex accent" :latin-small-letter-e-with-circumflex-accent)
    (000 235 "e with diaeresis" :latin-small-letter-e-with-diaeresis)
    (000 236 "i with grave accent" :latin-small-letter-i-with-grave-accent)
    (000 237 "i with acute accent" :latin-small-letter-i-with-acute-accent)
    (000 238 "i with circumflex accent" :latin-small-letter-i-with-circumflex-accent)
    (000 239 "i with diaeresis" :latin-small-letter-i-with-diaeresis)
    (000 240 "eth" :icelandic-small-letter-eth)
    (000 241 "n with tilde" :latin-small-letter-n-with-tilde)
    (000 242 "o with grave accent" :latin-small-letter-o-with-grave-accent)
    (000 243 "o with acute accent" :latin-small-letter-o-with-acute-accent)
    (000 244 "o with circumflex accent" :latin-small-letter-o-with-circumflex-accent)
    (000 245 "o with tilde" :latin-small-letter-o-with-tilde)
    (000 246 "o with diaeresis" :latin-small-letter-o-with-diaeresis)
    (000 247 "division sign" :division-sign)
    (000 248 "o with oblique stroke" :latin-small-letter-o-with-oblique-stroke)
    (000 249 "u with grave accent" :latin-small-letter-u-with-grave-accent)
    (000 250 "u with acute accent" :latin-small-letter-u-with-acute-accent)
    (000 251 "u with circumflex accent" :latin-small-letter-u-with-circumflex-accent)
    (000 252 "u with diaeresis" :latin-small-letter-u-with-diaeresis)
    (000 253 "y with acute accent" :latin-small-letter-y-with-acute-accent)
    (000 254 "thorn" :icelandic-small-letter-thorn)
    (000 255 "y with diaeresis" :latin-small-letter-y-with-diaeresis)
    (001 161 "A with ogonek" :latin-capital-letter-a-with-ogonek)
    (001 162 "breve" :breve)
    (001 163 "L with stroke" :latin-capital-letter-l-with-stroke)
    (001 165 "L with caron" :latin-capital-letter-l-with-caron)
    (001 166 "S with acute accent" :latin-capital-letter-s-with-acute-accent)
    (001 169 "S with caron" :latin-capital-letter-s-with-caron)
    (001 170 "S with cedilla" :latin-capital-letter-s-with-cedilla)
    (001 171 "T with caron" :latin-capital-letter-t-with-caron)
    (001 172 "Z with acute accent" :latin-capital-letter-z-with-acute-accent)
    (001 174 "Z with caron" :latin-capital-letter-z-with-caron)
    (001 175 "Z with dot above" :latin-capital-letter-z-with-dot-above)
    (001 177 "a with ogonek" :latin-small-letter-a-with-ogonek)
    (001 178 "ogonek" :ogonek)
    (001 179 "l with stroke" :latin-small-letter-l-with-stroke)
    (001 181 "l with caron" :latin-small-letter-l-with-caron)
    (001 182 "s with acute accent" :latin-small-letter-s-with-acute-accent)
    (001 183 "caron" :caron)
    (001 185 "s with caron" :latin-small-letter-s-with-caron)
    (001 186 "s with cedilla" :latin-small-letter-s-with-cedilla)
    (001 187 "t with caron" :latin-small-letter-t-with-caron)
    (001 188 "z with acute accent" :latin-small-letter-z-with-acute-accent)
    (001 189 "double acute accent" :double-acute-accent)
    (001 190 "z with caron" :latin-small-letter-z-with-caron)
    (001 191 "z with dot above" :latin-small-letter-z-with-dot-above)
    (001 192 "R with acute accent" :latin-capital-letter-r-with-acute-accent)
    (001 195 "A with breve" :latin-capital-letter-a-with-breve)
    (001 197 "L with acute accent" :latin-capital-letter-l-with-acute-accent)
    (001 198 "C with acute accent" :latin-capital-letter-c-with-acute-accent)
    (001 200 "C with caron" :latin-capital-letter-c-with-caron)
    (001 202 "E with ogonek" :latin-capital-letter-e-with-ogonek)
    (001 204 "E with caron" :latin-capital-letter-e-with-caron)
    (001 207 "D with caron" :latin-capital-letter-d-with-caron)
    (001 208 "D with stroke" :latin-capital-letter-d-with-stroke)
    (001 209 "N with acute accent" :latin-capital-letter-n-with-acute-accent)
    (001 210 "N with caron" :latin-capital-letter-n-with-caron)
    (001 213 "O with double acute accent" :latin-capital-letter-o-with-double-acute-accent)
    (001 216 "R with caron" :latin-capital-letter-r-with-caron)
    (001 217 "U with ring above" :latin-capital-letter-u-with-ring-above)
    (001 219 "U with double acute accent" :latin-capital-letter-u-with-double-acute-accent)
    (001 222 "T with cedilla" :latin-capital-letter-t-with-cedilla)
    (001 224 "r with acute accent" :latin-small-letter-r-with-acute-accent)
    (001 227 "a with breve" :latin-small-letter-a-with-breve)
    (001 229 "l with acute accent" :latin-small-letter-l-with-acute-accent)
    (001 230 "c with acute accent" :latin-small-letter-c-with-acute-accent)
    (001 232 "c with caron" :latin-small-letter-c-with-caron)
    (001 234 "e with ogonek" :latin-small-letter-e-with-ogonek)
    (001 236 "e with caron" :latin-small-letter-e-with-caron)
    (001 239 "d with caron" :latin-small-letter-d-with-caron)
    (001 240 "d with stroke" :latin-small-letter-d-with-stroke)
    (001 241 "n with acute accent" :latin-small-letter-n-with-acute-accent)
    (001 242 "n with caron" :latin-small-letter-n-with-caron)
    (001 245 "o with double acute accent" :latin-small-letter-o-with-double-acute-accent)
    (001 248 "r with caron" :latin-small-letter-r-with-caron)
    (001 249 "u with ring above" :latin-small-letter-u-with-ring-above)
    (001 251 "u with double acute accent" :latin-small-letter-u-with-double-acute-accent)
    (001 254 "t with cedilla" :latin-small-letter-t-with-cedilla)
    (001 255 "dot above" :dot-above)
    (002 161 "H with stroke" :latin-capital-letter-h-with-stroke)
    (002 166 "H with circumflex accent" :latin-capital-letter-h-with-circumflex-accent)
    (002 169 "I with dot above" :latin-capital-letter-i-with-dot-above)
    (002 171 "G with breve" :latin-capital-letter-g-with-breve)
    (002 172 "J with circumflex accent" :latin-capital-letter-j-with-circumflex-accent)
    (002 177 "h with stroke" :latin-small-letter-h-with-stroke)
    (002 182 "h with circumflex accent" :latin-small-letter-h-with-circumflex-accent)
    (002 185 "i" :small-dotless-letter-i)
    (002 187 "g with breve" :latin-small-letter-g-with-breve)
    (002 188 "j with circumflex accent" :latin-small-letter-j-with-circumflex-accent)
    (002 197 "C with dot above" :latin-capital-letter-c-with-dot-above)
    (002 198 "C with circumflex accent" :latin-capital-letter-c-with-circumflex-accent)
    (002 213 "G with dot above" :latin-capital-letter-g-with-dot-above)
    (002 216 "G with circumflex accent" :latin-capital-letter-g-with-circumflex-accent)
    (002 221 "U with breve" :latin-capital-letter-u-with-breve)
    (002 222 "S with circumflex accent" :latin-capital-letter-s-with-circumflex-accent)
    (002 229 "c with dot above" :latin-small-letter-c-with-dot-above)
    (002 230 "c with circumflex accent" :latin-small-letter-c-with-circumflex-accent)
    (002 245 "g with dot above" :latin-small-letter-g-with-dot-above)
    (002 248 "g with circumflex accent" :latin-small-letter-g-with-circumflex-accent)
    (002 253 "u with breve" :latin-small-letter-u-with-breve)
    (002 254 "s with circumflex accent" :latin-small-letter-s-with-circumflex-accent)
    (003 162 "kappa" :latin-small-letter-kappa)
    (003 163 "R with cedilla" :latin-capital-letter-r-with-cedilla)
    (003 165 "I with tilde" :latin-capital-letter-i-with-tilde)
    (003 166 "L with cedilla" :latin-capital-letter-l-with-cedilla)
    (003 170 "E with macron" :latin-capital-letter-e-with-macron)
    (003 171 "G with cedilla" :latin-capital-letter-g-with-cedilla)
    (003 172 "T with oblique stroke" :latin-capital-letter-t-with-oblique-stroke)
    (003 179 "r with cedilla" :latin-small-letter-r-with-cedilla)
    (003 181 "i with tilde" :latin-small-letter-i-with-tilde)
    (003 182 "l with cedilla" :latin-small-letter-l-with-cedilla)
    (003 186 "e with macron" :latin-small-letter-e-with-macron)
    (003 187 "g with acute accent" :latin-small-letter-g-with-acute-accent)
    (003 188 "t with oblique stroke" :latin-small-letter-t-with-oblique-stroke)
    (003 189 "ENG" :lappish-capital-letter-eng)
    (003 191 "eng" :lappish-small-letter-eng)
    (003 192 "A with macron" :latin-capital-letter-a-with-macron)
    (003 199 "I with ogonek" :latin-capital-letter-i-with-ogonek)
    (003 204 "E with dot above" :latin-capital-letter-e-with-dot-above)
    (003 207 "I with macron" :latin-capital-letter-i-with-macron)
    (003 209 "N with cedilla" :latin-capital-letter-n-with-cedilla)
    (003 210 "O with macron" :latin-capital-letter-o-with-macron)
    (003 211 "K with cedilla" :latin-capital-letter-k-with-cedilla)
    (003 217 "U with ogonek" :latin-capital-letter-u-with-ogonek)
    (003 221 "U with tilde" :latin-capital-letter-u-with-tilde)
    (003 222 "U with macron" :latin-capital-letter-u-with-macron)
    (003 224 "a with macron" :latin-small-letter-a-with-macron)
    (003 231 "i with ogonek" :latin-small-letter-i-with-ogonek)
    (003 236 "e with dot above" :latin-small-letter-e-with-dot-above)
    (003 239 "i with macron" :latin-small-letter-i-with-macron)
    (003 241 "n with cedilla" :latin-small-letter-n-with-cedilla)
    (003 242 "o with macron" :latin-small-letter-o-with-macron)
    (003 243 "k with cedilla" :latin-small-letter-k-with-cedilla)
    (003 249 "u with ogonek" :latin-small-letter-u-with-ogonek)
    (003 253 "u with tilde" :latin-small-letter-u-with-tilde)
    (003 254 "u with macron" :latin-small-letter-u-with-macron)
    (004 126 "overline" :overline)
    (004 161 "kana full stop" :kana-full-stop)
    (004 162 "kana opening bracket" :kana-opening-bracket)
    (004 163 "kana closing bracket" :kana-closing-bracket)
    (004 164 "kana comma" :kana-comma)
    (004 165 "kana middle dot" :kana-middle-dot)
    (004 166 "wo" :kana-letter-wo)
    (004 167 "small a" :kana-letter-small-a)
    (004 168 "small i" :kana-letter-small-i)
    (004 169 "small u" :kana-letter-small-u)
    (004 170 "small e" :kana-letter-small-e)
    (004 171 "small o" :kana-letter-small-o)
    (004 172 "small ya" :kana-letter-small-ya)
    (004 173 "small yu" :kana-letter-small-yu)
    (004 174 "small yo" :kana-letter-small-yo)
    (004 175 "small tu" :kana-letter-small-tu)
    (004 176 "prolonged sound symbol" :prolonged-sound-symbol)
    (004 177 "a" :kana-letter-a)
    (004 178 "i" :kana-letter-i)
    (004 179 "u" :kana-letter-u)
    (004 180 "e" :kana-letter-e)
    (004 181 "o" :kana-letter-o)
    (004 182 "ka" :kana-letter-ka)
    (004 183 "ki" :kana-letter-ki)
    (004 184 "ku" :kana-letter-ku)
    (004 185 "ke" :kana-letter-ke)
    (004 186 "ko" :kana-letter-ko)
    (004 187 "sa" :kana-letter-sa)
    (004 188 "shi" :kana-letter-shi)
    (004 189 "su" :kana-letter-su)
    (004 190 "se" :kana-letter-se)
    (004 191 "so" :kana-letter-so)
    (004 192 "ta" :kana-letter-ta)
    (004 193 "ti" :kana-letter-ti)
    (004 194 "tu" :kana-letter-tu)
    (004 195 "te" :kana-letter-te)
    (004 196 "to" :kana-letter-to)
    (004 197 "na" :kana-letter-na)
    (004 198 "ni" :kana-letter-ni)
    (004 199 "nu" :kana-letter-nu)
    (004 200 "ne" :kana-letter-ne)
    (004 201 "no" :kana-letter-no)
    (004 202 "ha" :kana-letter-ha)
    (004 203 "hi" :kana-letter-hi)
    (004 204 "hu" :kana-letter-hu)
    (004 205 "he" :kana-letter-he)
    (004 206 "ho" :kana-letter-ho)
    (004 207 "ma" :kana-letter-ma)
    (004 208 "mi" :kana-letter-mi)
    (004 209 "mu" :kana-letter-mu)
    (004 210 "me" :kana-letter-me)
    (004 211 "mo" :kana-letter-mo)
    (004 212 "ya" :kana-letter-ya)
    (004 213 "yu" :kana-letter-yu)
    (004 214 "yo" :kana-letter-yo)
    (004 215 "ra" :kana-letter-ra)
    (004 216 "ri" :kana-letter-ri)
    (004 217 "ru" :kana-letter-ru)
    (004 218 "re" :kana-letter-re)
    (004 219 "ro" :kana-letter-ro)
    (004 220 "wa" :kana-letter-wa)
    (004 221 "n" :kana-letter-n)
    (004 222 "voiced sound symbol" :voiced-sound-symbol)
    (004 223 "semi voiced sound symbol" :semi-voiced-sound-symbol)
    (005 172 "arabic comma" :arabic-comma)
    (005 187 "arabic semi colon" :arabic-semi-colon)
    (005 191 "arabic question mark" :arabic-question-mark)
    (005 193 "hamza" :arabic-letter-hamza)
    (005 194 "madda on alef" :arabic-letter-madda-on-alef)
    (005 195 "hamza on alef" :arabic-letter-hamza-on-alef)
    (005 196 "hamza on waw" :arabic-letter-hamza-on-waw)
    (005 197 "hamza under alef" :arabic-letter-hamza-under-alef)
    (005 198 "hamza on yeh" :arabic-letter-hamza-on-yeh)
    (005 199 "alef" :arabic-letter-alef)
    (005 200 "beh" :arabic-letter-beh)
    (005 201 "teh marbuta" :arabic-letter-teh-marbuta)
    (005 202 "teh" :arabic-letter-teh)
    (005 203 "theh" :arabic-letter-theh)
    (005 204 "jeem" :arabic-letter-jeem)
    (005 205 "hah" :arabic-letter-hah)
    (005 206 "khah" :arabic-letter-khah)
    (005 207 "dal" :arabic-letter-dal)
    (005 208 "thal" :arabic-letter-thal)
    (005 209 "ra" :arabic-letter-ra)
    (005 210 "zain" :arabic-letter-zain)
    (005 211 "seen" :arabic-letter-seen)
    (005 212 "sheen" :arabic-letter-sheen)
    (005 213 "sad" :arabic-letter-sad)
    (005 214 "dad" :arabic-letter-dad)
    (005 215 "tah" :arabic-letter-tah)
    (005 216 "zah" :arabic-letter-zah)
    (005 217 "ain" :arabic-letter-ain)
    (005 218 "ghain" :arabic-letter-ghain)
    (005 224 "tatweel" :arabic-letter-tatweel)
    (005 225 "feh" :arabic-letter-feh)
    (005 226 "qaf" :arabic-letter-qaf)
    (005 227 "kaf" :arabic-letter-kaf)
    (005 228 "lam" :arabic-letter-lam)
    (005 229 "meem" :arabic-letter-meem)
    (005 230 "noon" :arabic-letter-noon)
    (005 231 "heh" :arabic-letter-heh)
    (005 232 "waw" :arabic-letter-waw)
    (005 233 "alef maksura" :arabic-letter-alef-maksura)
    (005 234 "yeh" :arabic-letter-yeh)
    (005 235 "fathatan" :arabic-letter-fathatan)
    (005 236 "dammatan" :arabic-letter-dammatan)
    (005 237 "kasratan" :arabic-letter-kasratan)
    (005 238 "fatha" :arabic-letter-fatha)
    (005 239 "damma" :arabic-letter-damma)
    (005 240 "kasra" :arabic-letter-kasra)
    (005 241 "shadda" :arabic-letter-shadda)
    (005 242 "sukun" :arabic-letter-sukun)
    (006 161 "dje" :serbian-small-letter-dje)
    (006 162 "gje" :macedonia-small-letter-gje)
    (006 163 "io" :cyrillic-small-letter-io)
    (006 164 "je" :ukranian-small-letter-je)
    (006 165 "dse" :macedonia-small-letter-dse)
    (006 166 "i" :ukranian-small-letter-i)
    (006 167 "yi" :ukranian-small-letter-yi)
    (006 168 "je" :serbian-small-letter-je)
    (006 169 "lje" :serbian-small-letter-lje)
    (006 170 "nje" :serbian-small-letter-nje)
    (006 171 "tshe" :serbian-small-letter-tshe)
    (006 172 "kje" :macedonia-small-letter-kje)
    (006 174 "short u" :byelorussian-small-letter-short-u)
    (006 175 "dze" :serbian-small-letter-dze)
    (006 176 "numero sign" :numero-sign)
    (006 177 "DJE" :serbian-capital-letter-dje)
    (006 178 "GJE" :macedonia-capital-letter-gje)
    (006 179 "IO" :cyrillic-capital-letter-io)
    (006 180 "JE" :ukranian-capital-letter-je)
    (006 181 "DSE" :macedonia-capital-letter-dse)
    (006 182 "I" :ukranian-capital-letter-i)
    (006 183 "YI" :ukranian-capital-letter-yi)
    (006 184 "JE" :serbian-capital-letter-je)
    (006 185 "LJE" :serbian-capital-letter-lje)
    (006 186 "NJE" :serbian-capital-letter-nje)
    (006 187 "TSHE" :serbian-capital-letter-tshe)
    (006 188 "KJE" :macedonia-capital-letter-kje)
    (006 190 "SHORT u" :byelorussian-capital-letter-short-u)
    (006 191 "DZE" :serbian-capital-letter-dze)
    (006 192 "yu" :cyrillic-small-letter-yu)
    (006 193 "a" :cyrillic-small-letter-a)
    (006 194 "be" :cyrillic-small-letter-be)
    (006 195 "tse" :cyrillic-small-letter-tse)
    (006 196 "de" :cyrillic-small-letter-de)
    (006 197 "ie" :cyrillic-small-letter-ie)
    (006 198 "ef" :cyrillic-small-letter-ef)
    (006 199 "ghe" :cyrillic-small-letter-ghe)
    (006 200 "ha" :cyrillic-small-letter-ha)
    (006 201 "i" :cyrillic-small-letter-i)
    (006 202 "short i" :cyrillic-small-letter-short-i)
    (006 203 "ka" :cyrillic-small-letter-ka)
    (006 204 "el" :cyrillic-small-letter-el)
    (006 205 "em" :cyrillic-small-letter-em)
    (006 206 "en" :cyrillic-small-letter-en)
    (006 207 "o" :cyrillic-small-letter-o)
    (006 208 "pe" :cyrillic-small-letter-pe)
    (006 209 "ya" :cyrillic-small-letter-ya)
    (006 210 "er" :cyrillic-small-letter-er)
    (006 211 "es" :cyrillic-small-letter-es)
    (006 212 "te" :cyrillic-small-letter-te)
    (006 213 "u" :cyrillic-small-letter-u)
    (006 214 "zhe" :cyrillic-small-letter-zhe)
    (006 215 "ve" :cyrillic-small-letter-ve)
    (006 216 "cyrillic small soft sign" :cyrillic-small-soft-sign)
    (006 217 "yeru" :cyrillic-small-letter-yeru)
    (006 218 "ze" :cyrillic-small-letter-ze)
    (006 219 "sha" :cyrillic-small-letter-sha)
    (006 220 "e" :cyrillic-small-letter-e)
    (006 221 "shcha" :cyrillic-small-letter-shcha)
    (006 222 "che" :cyrillic-small-letter-che)
    (006 223 "cyrillic small hard sign" :cyrillic-small-hard-sign)
    (006 224 "YU" :cyrillic-capital-letter-yu)
    (006 225 "A" :cyrillic-capital-letter-a)
    (006 226 "BE" :cyrillic-capital-letter-be)
    (006 227 "TSE" :cyrillic-capital-letter-tse)
    (006 228 "DE" :cyrillic-capital-letter-de)
    (006 229 "IE" :cyrillic-capital-letter-ie)
    (006 230 "EF" :cyrillic-capital-letter-ef)
    (006 231 "GHE" :cyrillic-capital-letter-ghe)
    (006 232 "HA" :cyrillic-capital-letter-ha)
    (006 233 "I" :cyrillic-capital-letter-i)
    (006 234 "SHORT i" :cyrillic-capital-letter-short-i)
    (006 235 "KA" :cyrillic-capital-letter-ka)
    (006 236 "EL" :cyrillic-capital-letter-el)
    (006 237 "EM" :cyrillic-capital-letter-em)
    (006 238 "EN" :cyrillic-capital-letter-en)
    (006 239 "O" :cyrillic-capital-letter-o)
    (006 240 "PE" :cyrillic-capital-letter-pe)
    (006 241 "YA" :cyrillic-capital-letter-ya)
    (006 242 "ER" :cyrillic-capital-letter-er)
    (006 243 "ES" :cyrillic-capital-letter-es)
    (006 244 "TE" :cyrillic-capital-letter-te)
    (006 245 "U" :cyrillic-capital-letter-u)
    (006 246 "ZHE" :cyrillic-capital-letter-zhe)
    (006 247 "VE" :cyrillic-capital-letter-ve)
    (006 248 "SOFT SIGN" :cyrillic-capital-soft-sign)
    (006 249 "YERU" :cyrillic-capital-letter-yeru)
    (006 250 "ZE" :cyrillic-capital-letter-ze)
    (006 251 "SHA" :cyrillic-capital-letter-sha)
    (006 252 "E" :cyrillic-capital-letter-e)
    (006 253 "SHCHA" :cyrillic-capital-letter-shcha)
    (006 254 "CHE" :cyrillic-capital-letter-che)
    (006 255 "CYRILLIC capital hard sign" :cyrillic-capital-hard-sign)
    (007 161 "ALPHA with accent" :greek-capital-letter-alpha-with-accent)
    (007 162 "EPSILON with accent" :greek-capital-letter-epsilon-with-accent)
    (007 163 "ETA with accent" :greek-capital-letter-eta-with-accent)
    (007 164 "IOTA with accent" :greek-capital-letter-iota-with-accent)
    (007 165 "IOTA with diaeresis" :greek-capital-letter-iota-with-diaeresis)
    (007 166 "IOTA with accent+dieresis" :greek-capital-letter-iota-with-accent+dieresis)
    (007 167 "OMICRON with accent" :greek-capital-letter-omicron-with-accent)
    (007 168 "UPSILON with accent" :greek-capital-letter-upsilon-with-accent)
    (007 169 "UPSILON with dieresis" :greek-capital-letter-upsilon-with-dieresis)
    (007 170 "UPSILON with accent+dieresis" :greek-capital-letter-upsilon-with-accent+dieresis)
    (007 171 "OMEGA with accent" :greek-capital-letter-omega-with-accent)
    (007 177 "alpha with accent" :greek-small-letter-alpha-with-accent)
    (007 178 "epsilon with accent" :greek-small-letter-epsilon-with-accent)
    (007 179 "eta with accent" :greek-small-letter-eta-with-accent)
    (007 180 "iota with accent" :greek-small-letter-iota-with-accent)
    (007 181 "iota with dieresis" :greek-small-letter-iota-with-dieresis)
    (007 182 "iota with accent+dieresis" :greek-small-letter-iota-with-accent+dieresis)
    (007 183 "omicron with accent" :greek-small-letter-omicron-with-accent)
    (007 184 "upsilon with accent" :greek-small-letter-upsilon-with-accent)
    (007 185 "upsilon with dieresis" :greek-small-letter-upsilon-with-dieresis)
    (007 186 "upsilon with accent+dieresis" :greek-small-letter-upsilon-with-accent+dieresis)
    (007 187 "omega with accent" :greek-small-letter-omega-with-accent)
    (007 193 "ALPHA" :greek-capital-letter-alpha)
    (007 194 "BETA" :greek-capital-letter-beta)
    (007 195 "GAMMA" :greek-capital-letter-gamma)
    (007 196 "DELTA" :greek-capital-letter-delta)
    (007 197 "EPSILON" :greek-capital-letter-epsilon)
    (007 198 "ZETA" :greek-capital-letter-zeta)
    (007 199 "ETA" :greek-capital-letter-eta)
    (007 200 "THETA" :greek-capital-letter-theta)
    (007 201 "IOTA" :greek-capital-letter-iota)
    (007 202 "KAPPA" :greek-capital-letter-kappa)
    (007 203 "LAMBDA" :greek-capital-letter-lambda)
    (007 204 "MU" :greek-capital-letter-mu)
    (007 205 "NU" :greek-capital-letter-nu)
    (007 206 "XI" :greek-capital-letter-xi)
    (007 207 "OMICRON" :greek-capital-letter-omicron)
    (007 208 "PI" :greek-capital-letter-pi)
    (007 209 "RHO" :greek-capital-letter-rho)
    (007 210 "SIGMA" :greek-capital-letter-sigma)
    (007 212 "TAU" :greek-capital-letter-tau)
    (007 213 "UPSILON" :greek-capital-letter-upsilon)
    (007 214 "PHI" :greek-capital-letter-phi)
    (007 215 "CHI" :greek-capital-letter-chi)
    (007 216 "PSI" :greek-capital-letter-psi)
    (007 217 "OMEGA" :greek-capital-letter-omega)
    (007 225 "alpha" :greek-small-letter-alpha)
    (007 226 "beta" :greek-small-letter-beta)
    (007 227 "gamma" :greek-small-letter-gamma)
    (007 228 "delta" :greek-small-letter-delta)
    (007 229 "epsilon" :greek-small-letter-epsilon)
    (007 230 "zeta" :greek-small-letter-zeta)
    (007 231 "eta" :greek-small-letter-eta)
    (007 232 "theta" :greek-small-letter-theta)
    (007 233 "iota" :greek-small-letter-iota)
    (007 234 "kappa" :greek-small-letter-kappa)
    (007 235 "lambda" :greek-small-letter-lambda)
    (007 236 "mu" :greek-small-letter-mu)
    (007 237 "nu" :greek-small-letter-nu)
    (007 238 "xi" :greek-small-letter-xi)
    (007 239 "omicron" :greek-small-letter-omicron)
    (007 240 "pi" :greek-small-letter-pi)
    (007 241 "rho" :greek-small-letter-rho)
    (007 242 "sigma" :greek-small-letter-sigma)
    (007 243 "final small sigma" :greek-small-letter-final-small-sigma)
    (007 244 "tau" :greek-small-letter-tau)
    (007 245 "upsilon" :greek-small-letter-upsilon)
    (007 246 "phi" :greek-small-letter-phi)
    (007 247 "chi" :greek-small-letter-chi)
    (007 248 "psi" :greek-small-letter-psi)
    (007 249 "omega" :greek-small-letter-omega)
    (008 161 "left radical" :left-radical)
    (008 162 "top left radical" :top-left-radical)
    (008 163 "horizontal connector" :horizontal-connector)
    (008 164 "top integral" :top-integral)
    (008 165 "bottom integral" :bottom-integral)
    (008 166 "vertical connector" :vertical-connector)
    (008 167 "top left square bracket" :top-left-square-bracket)
    (008 168 "bottom left square bracket" :bottom-left-square-bracket)
    (008 169 "top right square bracket" :top-right-square-bracket)
    (008 170 "bottom right square bracket" :bottom-right-square-bracket)
    (008 171 "top left parenthesis" :top-left-parenthesis)
    (008 172 "bottom left parenthesis" :bottom-left-parenthesis)
    (008 173 "top right parenthesis" :top-right-parenthesis)
    (008 174 "bottom right parenthesis" :bottom-right-parenthesis)
    (008 175 "left middle curly brace" :left-middle-curly-brace)
    (008 176 "right middle curly brace" :right-middle-curly-brace)
    (008 177 "top left summation" :top-left-summation)
    (008 178 "bottom left summation" :bottom-left-summation)
    (008 179 "top vertical summation connector" :top-vertical-summation-connector)
    (008 180 "bottom vertical summation connector" :bottom-vertical-summation-connector)
    (008 181 "top right summation" :top-right-summation)
    (008 182 "bottom right summation" :bottom-right-summation)
    (008 183 "right middle summation" :right-middle-summation)
    (008 188 "less than or equal sign" :less-than-or-equal-sign)
    (008 189 "not equal sign" :not-equal-sign)
    (008 190 "greater than or equal sign" :greater-than-or-equal-sign)
    (008 191 "integral" :integral)
    (008 192 "therefore" :therefore)
    (008 193 "variation" :variation :proportional-to)
    (008 194 "infinity" :infinity)
    (008 197 "nabla" :nabla :del)
    (008 200 "is approximate to" :is-approximate-to)
    (008 201 "similar or equal to" :similar-or-equal-to)
    (008 205 "if and only if" :if-and-only-if)
    (008 206 "implies" :implies)
    (008 207 "identical to" :identical-to)
    (008 214 "radical" :radical)
    (008 218 "is included in" :is-included-in)
    (008 219 "includes" :includes)
    (008 220 "intersection" :intersection)
    (008 221 "union" :union)
    (008 222 "logical and" :logical-and)
    (008 223 "logical or" :logical-or)
    (008 239 "partial derivative" :partial-derivative)
    (008 246 "function" :function)
    (008 251 "left arrow" :left-arrow)
    (008 252 "upward arrow" :upward-arrow)
    (008 253 "right arrow" :right-arrow)
    (008 254 "downward arrow" :downward-arrow)
    (009 223 "blank" :blank)
    (009 224 "solid diamond" :solid-diamond)
    (009 225 "checkerboard" :checkerboard)
    (009 226 "ht" :ht)
    (009 227 "ff" :ff)
    (009 228 "cr" :cr)
    (009 229 "lf" :lf)
    (009 232 "nl" :nl)
    (009 233 "vt" :vt)
    (009 234 "lower right corner" :lower-right-corner)
    (009 235 "upper right corner" :upper-right-corner)
    (009 236 "upper left corner" :upper-left-corner)
    (009 237 "lower left corner" :lower-left-corner)
    (009 238 "crossing lines" :crossing-lines)
    (009 239 "horizontal line scan 1" :horizontal-line-scan-1)
    (009 240 "horizontal line scan 3" :horizontal-line-scan-3)
    (009 241 "horizontal line scan 5" :horizontal-line-scan-5)
    (009 242 "horizontal line scan 7" :horizontal-line-scan-7)
    (009 243 "horizontal line scan 9" :horizontal-line-scan-9)
    (009 244 "left t" :left-t)
    (009 245 "right t" :right-t)
    (009 246 "bottom t" :bottom-t)
    (009 247 "top t" :top-t)
    (009 248 "vertical bar" :vertical-bar)
    (010 161 "em space" :em-space)
    (010 162 "en space" :en-space)
    (010 163 "3/em space" :3/em-space)
    (010 164 "4/em space" :4/em-space)
    (010 165 "digit space" :digit-space)
    (010 166 "punctuation space" :punctuation-space)
    (010 167 "thin space" :thin-space)
    (010 168 "hair space" :hair-space)
    (010 169 "em dash" :em-dash)
    (010 170 "en dash" :en-dash)
    (010 172 "significant blank symbol" :significant-blank-symbol)
    (010 174 "ellipsis" :ellipsis)
    (010 175 "double baseline dot" :double-baseline-dot)
    (010 176 "vulgar fraction one third" :vulgar-fraction-one-third)
    (010 177 "vulgar fraction two thirds" :vulgar-fraction-two-thirds)
    (010 178 "vulgar fraction one fifth" :vulgar-fraction-one-fifth)
    (010 179 "vulgar fraction two fifths" :vulgar-fraction-two-fifths)
    (010 180 "vulgar fraction three fifths" :vulgar-fraction-three-fifths)
    (010 181 "vulgar fraction four fifths" :vulgar-fraction-four-fifths)
    (010 182 "vulgar fraction one sixth" :vulgar-fraction-one-sixth)
    (010 183 "vulgar fraction five sixths" :vulgar-fraction-five-sixths)
    (010 184 "care of" :care-of)
    (010 187 "figure dash" :figure-dash)
    (010 188 "left angle bracket" :left-angle-bracket)
    (010 189 "decimal point" :decimal-point)
    (010 190 "right angle bracket" :right-angle-bracket)
    (010 191 "marker" :marker)
    (010 195 "vulgar fraction one eighth" :vulgar-fraction-one-eighth)
    (010 196 "vulgar fraction three eighths" :vulgar-fraction-three-eighths)
    (010 197 "vulgar fraction five eighths" :vulgar-fraction-five-eighths)
    (010 198 "vulgar fraction seven eighths" :vulgar-fraction-seven-eighths)
    (010 201 "trademark sign" :trademark-sign)
    (010 202 "signature mark" :signature-mark)
    (010 203 "trademark sign in circle" :trademark-sign-in-circle)
    (010 204 "left open triangle" :left-open-triangle)
    (010 205 "right open triangle" :right-open-triangle)
    (010 206 "em open circle" :em-open-circle)
    (010 207 "em open rectangle" :em-open-rectangle)
    (010 208 "left single quotation mark" :left-single-quotation-mark)
    (010 209 "right single quotation mark" :right-single-quotation-mark)
    (010 210 "left double quotation mark" :left-double-quotation-mark)
    (010 211 "right double quotation mark" :right-double-quotation-mark)
    (010 212 "prescription" :prescription :take :recipe)
    (010 214 "minutes" :minutes)
    (010 215 "seconds" :seconds)
    (010 217 "latin cross" :latin-cross)
    (010 218 "hexagram" :hexagram)
    (010 219 "filled rectangle bullet" :filled-rectangle-bullet)
    (010 220 "filled left triangle bullet" :filled-left-triangle-bullet)
    (010 221 "filled right triangle bullet" :filled-right-triangle-bullet)
    (010 222 "em filled circle" :em-filled-circle)
    (010 223 "em filled rectangle" :em-filled-rectangle)
    (010 224 "en open circle bullet" :en-open-circle-bullet)
    (010 225 "en open square bullet" :en-open-square-bullet)
    (010 226 "open rectangular bullet" :open-rectangular-bullet)
    (010 227 "open triangular bullet up" :open-triangular-bullet-up)
    (010 228 "open triangular bullet down" :open-triangular-bullet-down)
    (010 229 "open star" :open-star)
    (010 230 "en filled circle bullet" :en-filled-circle-bullet)
    (010 231 "en filled square bullet" :en-filled-square-bullet)
    (010 232 "filled triangular bullet up" :filled-triangular-bullet-up)
    (010 233 "filled triangular bullet down" :filled-triangular-bullet-down)
    (010 234 "left pointer" :left-pointer)
    (010 235 "right pointer" :right-pointer)
    (010 236 "club" :club)
    (010 237 "diamond" :diamond)
    (010 238 "heart" :heart)
    (010 240 "maltese cross" :maltese-cross)
    (010 241 "dagger" :dagger)
    (010 242 "double dagger" :double-dagger)
    (010 243 "check mark" :check-mark :tick)
    (010 244 "ballot cross" :ballot-cross)
    (010 245 "musical sharp" :musical-sharp)
    (010 246 "musical flat" :musical-flat)
    (010 247 "male symbol" :male-symbol)
    (010 248 "female symbol" :female-symbol)
    (010 249 "telephone symbol" :telephone-symbol)
    (010 250 "telephone recorder symbol" :telephone-recorder-symbol)
    (010 251 "phonograph copyright sign" :phonograph-copyright-sign)
    (010 252 "caret" :caret)
    (010 253 "single low quotation mark" :single-low-quotation-mark)
    (010 254 "double low quotation mark" :double-low-quotation-mark)
    (010 255 "cursor" :cursor)
    (011 163 "left caret" :left-caret)
    (011 166 "right caret" :right-caret)
    (011 168 "down caret" :down-caret)
    (011 169 "up caret" :up-caret)
    (011 192 "overbar" :overbar)
    (011 194 "down tack" :down-tack)
    (011 195 "up shoe cap" :up-shoe-cap)
    (011 196 "down stile" :down-stile)
    (011 198 "underbar" :underbar)
    (011 202 "jot" :jot)
    (011 204 "quad" :quad)
    (011 206 "up tack" :up-tack)
    (011 207 "circle" :circle)
    (011 211 "up stile" :up-stile)
    (011 214 "down shoe cup" :down-shoe-cup)
    (011 216 "right shoe" :right-shoe)
    (011 218 "left shoe" :left-shoe)
    (011 220 "left tack" :left-tack)
    (011 252 "right tack" :right-tack)
    (012 224 "aleph" :hebrew-letter-aleph)
    (012 225 "beth" :hebrew-letter-beth)
    (012 226 "gimmel" :hebrew-letter-gimmel)
    (012 227 "daleth" :hebrew-letter-daleth)
    (012 228 "he" :hebrew-letter-he)
    (012 229 "waw" :hebrew-letter-waw)
    (012 230 "zayin" :hebrew-letter-zayin)
    (012 231 "het" :hebrew-letter-het)
    (012 232 "teth" :hebrew-letter-teth)
    (012 233 "yod" :hebrew-letter-yod)
    (012 234 "final kaph" :hebrew-letter-final-kaph)
    (012 235 "kaph" :hebrew-letter-kaph)
    (012 236 "lamed" :hebrew-letter-lamed)
    (012 237 "final mem" :hebrew-letter-final-mem)
    (012 238 "mem" :hebrew-letter-mem)
    (012 239 "final nun" :hebrew-letter-final-nun)
    (012 240 "nun" :hebrew-letter-nun)
    (012 241 "samekh" :hebrew-letter-samekh)
    (012 242 "a yin" :hebrew-letter-a-yin)
    (012 243 "final pe" :hebrew-letter-final-pe)
    (012 244 "pe" :hebrew-letter-pe)
    (012 245 "final zadi" :hebrew-letter-final-zadi)
    (012 246 "zadi" :hebrew-letter-zadi)
    (012 247 "hebrew kuf" :hebrew-kuf)
    (012 248 "hebrew resh" :hebrew-resh)
    (012 249 "hebrew shin" :hebrew-shin)
    (012 250 "hebrew taf" :hebrew-taf)
    (254 003 "iso level3 shift" :iso-level3-shift)
    (254 081 "dead acute" :dead-acute)
    (254 082 "dead circumflex" :dead-circumflex)
    (255 008 "backspace" :backspace :back-space :back-char)
    (255 009 "tab" :tab)
    (255 010 "linefeed" :linefeed)
    (255 011 "clear" :clear)
    (255 013 "return" :return :enter)
    (255 019 "pause" :pause :hold :scroll-lock)
    (255 027 "escape" :escape)
    (255 032 "multi key character preface" :multi-key-character-preface)
    (255 033 "kanji" :kanji :kanji-convert)
    (255 080 "home" :home)
    (255 081 "left" :left :move-left)
    (255 082 "up" :up :move-up :up-arrow)
    (255 083 "right" :right :move-right)
    (255 084 "down" :down :move-down :down-arrow)
    (255 085 "prior" :prior :previous)
    (255 086 "next" :next)
    (255 087 "end" :end :eol)
    (255 088 "begin" :begin :bol)
    (255 096 "select" :select :mark)
    (255 097 "print" :print)
    (255 098 "execute" :execute :run :do)
    (255 099 "insert" :insert :insert-here)
    (255 101 "undo" :undo :oops)
    (255 102 "redo" :redo :again)
    (255 103 "menu" :menu)
    (255 104 "find" :find :search)
    (255 105 "cancel" :cancel :stop :abort :exit)
    (255 106 "help" :help)
    (255 107 "break" :break)
    (255 126 "mode switch" :mode-switch :script-switch :character-set-switch)
    (255 127 "num lock" :num-lock)
    (255 128 " " :keypad-space)
    (255 137 "tab" :keypad-tab)
    (255 141 "enter" :keypad-enter)
    (255 145 "f1" :keypad-f1 :pf1 :a)
    (255 146 "f2" :keypad-f2 :pf2 :b)
    (255 147 "f3" :keypad-f3 :pf3 :c)
    (255 148 "f4" :keypad-f4 :pf4 :d)
    (255 149 "Keypad Home" :keypad-home)
    (255 150 "Keypad Left" :keypad-left)
    (255 151 "Keypad Up" :keypad-up)
    (255 152 "Keypad Right" :keypad-right)
    (255 153 "Keypad Down" :keypad-down)
    (255 154 "Keypad Prior" :keypad-prior)
    (255 155 "Keypad Next" :keypad-next)
    (255 156 "Keypad End" :keypad-end)
    (255 157 "Keypad Begin" :keypad-begin)
    (255 158 "Keypad Insert" :keypad-insert)
    (255 159 "Keypad Delete" :keypad-delete)
    (255 170 "*" :keypad-multiplication-sign)
    (255 171 "+" :keypad-plus-sign)
    (255 172 "keypad separator" :keypad-separator)
    (255 173 "-" :keypad-minus-sign)
    (255 174 "." :keypad-decimal-point)
    (255 175 "/" :keypad-division-sign)
    (255 176 "0" :keypad-digit-zero)
    (255 177 "1" :keypad-digit-one)
    (255 178 "2" :keypad-digit-two)
    (255 179 "3" :keypad-digit-three)
    (255 180 "4" :keypad-digit-four)
    (255 181 "5" :keypad-digit-five)
    (255 182 "6" :keypad-digit-six)
    (255 183 "7" :keypad-digit-seven)
    (255 184 "8" :keypad-digit-eight)
    (255 185 "9" :keypad-digit-nine)
    (255 189 "=" :keypad-equals-sign)
    (255 190 "f1" :f1)
    (255 191 "f2" :f2)
    (255 192 "f3" :f3)
    (255 193 "f4" :f4)
    (255 194 "f5" :f5)
    (255 195 "f6" :f6)
    (255 196 "f7" :f7)
    (255 197 "f8" :f8)
    (255 198 "f9" :f9)
    (255 199 "f10" :f10)
    (255 200 "f11" :f11 :l1)
    (255 201 "f12" :f12 :l2)
    (255 202 "f13" :f13 :l3)
    (255 203 "f14" :f14 :l4)
    (255 204 "f15" :f15 :l5)
    (255 205 "f16" :f16 :l6)
    (255 206 "f17" :f17 :l7)
    (255 207 "f18" :f18 :l8)
    (255 208 "f19" :f19 :l9)
    (255 209 "f20" :f20 :l10)
    (255 210 "f21" :f21 :r1)
    (255 211 "f22" :f22 :r2)
    (255 212 "f23" :f23 :r3)
    (255 213 "f24" :f24 :r4)
    (255 214 "f25" :f25 :r5)
    (255 215 "f26" :f26 :r6)
    (255 216 "f27" :f27 :r7)
    (255 217 "f28" :f28 :r8)
    (255 218 "f29" :f29 :r9)
    (255 219 "f30" :f30 :r10)
    (255 220 "f31" :f31 :r11)
    (255 221 "f32" :f32 :r12)
    (255 222 "f33" :f33 :r13)
    (255 223 "f34" :f34 :r14)
    (255 224 "f35" :f35 :r15)
    (255 225 "left shift" :left-shift)
    (255 226 "right shift" :right-shift)
    (255 227 "left control" :left-control)
    (255 228 "right control" :right-control)
    (255 229 "caps lock" :caps-lock)
    (255 230 "shift lock" :shift-lock)
    (255 231 "left meta" :left-meta)
    (255 232 "right meta" :right-meta)
    (255 233 "left alt" :left-alt)
    (255 234 "right alt" :right-alt)
    (255 235 "left super" :left-super)
    (255 236 "right super" :right-super)
    (255 237 "left hyper" :left-hyper)
    (255 238 "right hyper" :right-hyper)
    (255 255 "delete" :delete :rubout)))

(defparameter *keysym-name-table* (make-keysym-name-table *keysym-name-list*))
(defparameter *keysym-legend-table* (make-keysym-legend-table *keysym-name-list*))
(defparameter *name-keysym-table* (make-name-keysym-table *keysym-name-list*))

;========================
(SCT:BEGIN-PATCH-SECTION)
(SCT:PATCH-SECTION-ATTRIBUTES
  "-*- Mode: Lisp; Package: X-SCREEN; Syntax: Common-Lisp; Lowercase: Yes -*-")

(defun maybe-define-signature (&optional display)
  (unless display (setq display (x-screen::x-console-display sys:*console*)))
  (let (
;    (display (unless display
;		   (x-screen::x-console-display sys:*console*)))
	vendor-name
	codes
	(german nil))
    (setq vendor-name (xlib:display-vendor-name display))
    (setq codes (x-screen::display-keyboard-signature-keys display))
    (loop for l in codes
	  do
      (when (member ':LATIN-SMALL-LETTER-U-WITH-DIAERESIS l) (setq german t)))
    (append
      (list 'x-screen:define-keyboard-signature
	    (if german ':Xorg-pc-german ':Xorg-pc)
	    (list ':vendor-name vendor-name ':keycode-offset 0))
      codes)))
;;      (list ':german german))))

;;;
;;; eval this into buffer to get your keyboard def
;;;
;;; (maybe-define-signature)
;;;
(eval (maybe-define-signature))
;;;
(defun display-keyboard-layout-type (display)
  (declare (values layout-type keycode-offset))
  (eval (maybe-define-signature display))
  (multiple-value-bind (vendor-name vendor-version)
      (xlib:display-vendor display)
    (let ((keys (display-keyboard-signature-keys display)))
      (loop with highest-score = -1
	    with highest-scoring-keyboard-signature = nil
	    for keyboard-signature in *keyboard-signatures*
	    for score =
		(compare-keyboard-signature-keys
		  (keyboard-signature-vendor-name keyboard-signature)
		  (keyboard-signature-vendor-version keyboard-signature)
		  (keyboard-signature-keys keyboard-signature)
		  vendor-name vendor-version keys)
	    when (> score highest-score)
	      do (setq highest-score score)
		 (setq highest-scoring-keyboard-signature keyboard-signature)
	    finally
	      (when (> highest-score .75s0)
		(return
		  (values
		    (keyboard-signature-name highest-scoring-keyboard-signature)
		    (keyboard-signature-keycode-offset highest-scoring-keyboard-signature))))
	      ))))



;#+vlm
(x-screen:define-keyboard-mapping :Xorg-pc-german 
				  (:leds ((3 :caps-lock)
					  (4 :scroll-lock)
					  (5 :num-lock)))

;;;
;;; standard vlm codes
;;;
  (:f1  #\Select #\Square)
  (:f2  #\Network #\Circle)
  (:f3  #\Function #\Triangle)
  (:f4  #\Suspend (:mode-lock :locking t))
  (:f5  #\Resume)
  (:f6  #\Abort)
  (:f7  :left-super)
  (:f8  :left-hyper)
  (:f9  #\Scroll #\Page)
  (:f10 #\Clear-Input #\Refresh)
  (:f11 #\Complete #\End)
  (:f12 #\Help)
;;;
;;; do something reasonable with the keypad
;;; ??? num-lock ???
;;; for now, keypad numbers are on shift
;;;
  (:keypad-home #\Keyboard:Home #\7)
  (:keypad-up #\Keyboard:Up #\8)
  (:keypad-prior #\Keyboard:Back-Scroll #\9)
  (:keypad-minus-sign #\Keyboard:Copy #\-)
  (:keypad-left #\Keyboard:Left #\4)
  (:keypad-begin #\Space #\5 #\Space #\5)
  (:keypad-right #\Keyboard:Right #\6)
  (:keypad-plus-sign #\+ #\+)
  (:keypad-end #\End #\1)
  (:keypad-down #\Keyboard:Down #\2)
  (:keypad-next #\Scroll #\3 #\Page)
  (:keypad-insert #\0 #\0)
  (:keypad-delete #\Rubout #\,)
  (:keypad-division-sign #\Keyboard:Paste #\/)
  (:keypad-multiplication-sign #\Keyboard:Cut #\*)
  (:keypad-decimal-point #\Rubout #\.)
  (:keypad-enter #\Linefeed #\Return)
;;;
;;; special keys directly mappable
;;; :prior should map to m-scroll (how ??)
;;;
  (:home     #\Keyboard:Home)
  (:up       #\Keyboard:Up)
  (:left     #\Keyboard:Left)
  (:right    #\Keyboard:Right)
  (:down     #\Keyboard:Down)
  (:print    #\Keyboard:Print)
  (:undo     #\Keyboard:Undo)
  (:redo     #\Keyboard:Redo)
  (:find     #\Keyboard:Find)
  (:next     #\Scroll #\Page)
  (:prior    #\Keyboard:Back-Scroll #\Scroll)
  (:break    #\Suspend)
;;;
;;; right menu key to right-hyper
;;;
  (:menu     :right-hyper)
;;;
;;; num-lock is a mystery still
;;
    (:num-lock (:num-lock :locking t))
    (:caps-lock (:caps-lock :locking t))
;;;
;;; map Umlaute to their us keyboard equivalents
;;; won't display anyway because of no font glyphs
;;;
  (:latin-small-letter-u-with-diaeresis #\\ #\|)
  (:latin-small-letter-o-with-diaeresis #\[ #\{)
  (:latin-small-letter-a-with-diaeresis #\] #\})
;;;
;;; AltGr maps to right-symbol (to get "\{[]}@|~" going)
;;;
  (:iso-level3-shift :right-symbol)
;;;
;;; remap AltGr based keys to :right-symbol combinations
;;; conflicting symbols moved to shift-symbol
;;;
  (:german-small-letter-sharp-s #\space #\? #\\)
  (:digit-seven #\7 #\/ #\{)
  (:digit-eight #\8 #\( #\[)
  (:digit-nine #\9 #\) #\])
  (:digit-zero #\0 #\= #\} #\)
  (:latin-small-letter-q #\q #\Q #\@ #\)
  (:plus-sign #\+ #\* #\~)
  (:less-than-sign #\< #\> #\|)
  ;;
  ;; dead circumflex / degree
  ;; dead acute / grave
  ;;
  (:dead-circumflex #\^ #\ )
  (:dead-acute #\` #\')
  )

(x-screen:define-keyboard-mapping :Xorg-pc
				  (:leds ((3 :caps-lock)
					  (4 :scroll-lock)
					  (5 :num-lock)))

;;;
;;; standard vlm codes
;;;
  (:f1  #\Select #\Square)
  (:f2  #\Network #\Circle)
  (:f3  #\Function #\Triangle)
  (:f4  #\Suspend (:mode-lock :locking t))
  (:f5  #\Resume)
  (:f6  #\Abort)
  (:f7  :left-super)
  (:f8  :left-hyper)
  (:f9  #\Scroll #\Page)
  (:f10 #\Clear-Input #\Refresh)
  (:f11 #\Complete #\End)
  (:f12 #\Help)
;;;
;;; do something reasonable with the keypad
;;; ??? num-lock ???
;;; for now, keypad numbers are on shift
;;;
  (:keypad-home #\Keyboard:Home #\7)
  (:keypad-up #\Keyboard:Up #\8)
  (:keypad-prior #\Keyboard:Back-Scroll #\9)
  (:keypad-minus-sign #\Keyboard:Copy #\-)
  (:keypad-left #\Keyboard:Left #\4)
  (:keypad-begin #\Space #\5 #\Space #\5)
  (:keypad-right #\Keyboard:Right #\6)
  (:keypad-plus-sign #\+ #\+)
  (:keypad-end #\End #\1)
  (:keypad-down #\Keyboard:Down #\2)
  (:keypad-next #\Scroll #\3 #\Page)
  (:keypad-insert #\0 #\0)
  (:keypad-delete #\Rubout #\,)
  (:keypad-division-sign #\Keyboard:Paste #\/)
  (:keypad-multiplication-sign #\Keyboard:Cut #\*)
  (:keypad-decimal-point #\Rubout #\.)
  (:keypad-enter #\Linefeed #\Return)
;;;
;;; special keys directly mappable
;;; :prior should map to m-scroll (how ??)
;;;
  (:home     #\Keyboard:Home)
  (:up       #\Keyboard:Up)
  (:left     #\Keyboard:Left)
  (:right    #\Keyboard:Right)
  (:down     #\Keyboard:Down)
  (:print    #\Keyboard:Print)
  (:undo     #\Keyboard:Undo)
  (:redo     #\Keyboard:Redo)
  (:find     #\Keyboard:Find)
  (:next     #\Scroll #\Page)
  (:prior    #\Keyboard:Back-Scroll #\Scroll)
  (:break    #\Suspend)
;;;
;;; right menu key to right-hyper
;;;
  (:menu     :right-hyper)
;;;
;;; num-lock is a mystery still
;;
    (:num-lock (:num-lock :locking t))
    (:caps-lock (:caps-lock :locking t))
;;;
;;; map Umlaute to their us keyboard equivalents
;;; won't display anyway because of no font glyphs
;;;
;;  (:latin-small-letter-u-with-diaeresis #\\ #\|)
;;  (:latin-small-letter-o-with-diaeresis #\[ #\{)
;;  (:latin-small-letter-a-with-diaeresis #\] #\})
;;;
;;; AltGr maps to right-symbol (to get "\{[]}@|~" going)
;;;
;;  (:iso-level3-shift :right-symbol)
;;;
;;; remap AltGr based keys to :right-symbol combinations
;;; conflicting symbols moved to shift-symbol
;;;
;  (:german-small-letter-sharp-s #\space #\? #\\)
;  (:digit-seven #\7 #\/ #\{)
;  (:digit-eight #\8 #\( #\[)
;  (:digit-nine #\9 #\) #\])
;  (:digit-zero #\0 #\= #\} #\)
;  (:latin-small-letter-q #\q #\Q #\@ #\)
;  (:plus-sign #\+ #\* #\~)
;  (:less-than-sign #\< #\> #\|)
  ;;
  ;; dead circumflex / degree
  ;; dead acute / grave
  ;;
  (:dead-circumflex #\^ #\ )
  (:dead-acute #\` #\')
  )
