/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifuntran.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

.align 5
.globl NativeException
.ent NativeException 0
.align 3
NativeException:
        ldq	$1, PROCESSORSTATE_LINKAGE($14)	# Load linkage to escape block [1]
        ldq	$0, PROCESSORSTATE_RESUMEEMA($14)	# Re-load resumemulator [1]
        ldq	$12, PROCESSORSTATE_RESTARTSP($14)	# Restore SP (Just in case?) [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        ret	$31, ($1), 0	# Escape [1]
.end NativeException
.align 12
        and	$31, $31, $31 	# [3]
.align 12
.align 5
.globl PadPastAref1
.ent PadPastAref1 0
.align 3
PadPastAref1:
        ldq	$1, PROCESSORSTATE_LINKAGE($14)	# Load linkage to escape block [1-]
        ldq	$0, PROCESSORSTATE_RESUMEEMA($14)	# Re-load resumemulator [1]
        ldq	$12, PROCESSORSTATE_RESTARTSP($14)	# Restore SP (Just in case?) [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        ldq	$1, PROCESSORSTATE_LINKAGE($14)	# Load linkage to escape block [1]
        ldq	$0, PROCESSORSTATE_RESUMEEMA($14)	# Re-load resumemulator [1]
        ldq	$12, PROCESSORSTATE_RESTARTSP($14)	# Restore SP (Just in case?) [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        ret	$31, ($1), 0	# Escape [1]
.end PadPastAref1
.align 5
.globl CarSubroutine
.ent CarSubroutine 11
.align 3
CarSubroutine:
        lda	$30, -8($30)	#  [1-]
	.frame $30, 8, $0
        stq	$0, PROCESSORSTATE_LINKAGE($14)	#  [0di]
        ldq	$24, PROCESSORSTATE_STACKCACHEBASEVMA($14)	#  [1]
        ldl	$25, PROCESSORSTATE_SCOVLIMIT($14)	# Size of the stack cache (words) [1]
        addq	$0, 4, $0 	# [1-]
        stq	$12, PROCESSORSTATE_RESTARTSP($14)	#  [0di]
        stq	$0, 0($30)	#  [1]
	bsr	$0, CarInternal
        ldq	$0, 0($30)	#  [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        lda	$30, 8($30)	#  [0di]
        ret	$31, ($0), 1	# [2-]
.end CarSubroutine
.align 5
.globl CdrSubroutine
.ent CdrSubroutine 11
.align 3
CdrSubroutine:
        lda	$30, -8($30)	#  [1-]
	.frame $30, 8, $0
        stq	$0, PROCESSORSTATE_LINKAGE($14)	#  [0di]
        ldq	$24, PROCESSORSTATE_STACKCACHEBASEVMA($14)	#  [1]
        ldl	$25, PROCESSORSTATE_SCOVLIMIT($14)	# Size of the stack cache (words) [1]
        addq	$0, 4, $0 	# [1-]
        stq	$12, PROCESSORSTATE_RESTARTSP($14)	#  [0di]
        stq	$0, 0($30)	#  [1]
	bsr	$0, CdrInternal
        ldq	$0, 0($30)	#  [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        lda	$30, 8($30)	#  [0di]
        ret	$31, ($0), 1	# [2-]
.end CdrSubroutine
.align 5
.globl CarCdrSubroutine
.ent CarCdrSubroutine 13
.align 3
CarCdrSubroutine:
        lda	$30, -8($30)	#  [1-]
	.frame $30, 8, $0
        stq	$0, PROCESSORSTATE_LINKAGE($14)	#  [0di]
        ldq	$24, PROCESSORSTATE_STACKCACHEBASEVMA($14)	#  [1]
        ldl	$25, PROCESSORSTATE_SCOVLIMIT($14)	# Size of the stack cache (words) [1]
        addq	$0, 4, $0 	# [1-]
        stq	$12, PROCESSORSTATE_RESTARTSP($14)	#  [0di]
        stq	$0, 0($30)	#  [1]
	bsr	$0, CarCdrInternal
        ldq	$0, 0($30)	#  [1]
        stq	$31, PROCESSORSTATE_LINKAGE($14)	#  [1]
        lda	$30, 8($30)	#  [0di]
        ret	$31, ($0), 1	# [2-]
.end CarCdrSubroutine


/* End of file automatically generated from ../alpha-emulator/ifuntran.as */
